"""
Validator Component
Responsible for validating plans generated by the planner.
"""
from typing import List, Optional, Dict, Any
import logging

from ..contracts.user_request import UserRequest
from ..contracts.request_context import RequestContext
from ..contracts.agent_plan import AgentPlan
from ..contracts.planned_operation import PlannedOperation
from ..contracts.validation_result import ValidationResult


class ValidatorComponent:
    """
    Validator component responsible for validating plans generated by the planner.

    The validator checks that plans are safe, feasible, and conform to system constraints
    before allowing execution to proceed.
    """

    def __init__(self):
        self.logger = logging.getLogger("agent.validator")
        self.logger.info("Initializing ValidatorComponent")
        self._ready = False
        # Define allowed capabilities
        self._allowed_capabilities = {
            "leaf_segmentation",
            "disease_classification",
            "disease_segmentation",
            "severity",
            "explainability",
            "video_tracking",
            "plant_aggregator",
            "plant_analysis"
        }

    def initialize(self) -> None:
        """Initialize the validator component."""
        self.logger.info("ValidatorComponent initialized")
        self._ready = True

    def is_ready(self) -> bool:
        """Check if the validator component is ready.

        Returns:
            bool: True if component is ready, False otherwise
        """
        return self._ready

    def get_component_name(self) -> str:
        """Get the component name.

        Returns:
            str: Component name
        """
        return "ValidatorComponent"

    def validate_plan(self, user_request: UserRequest, request_context: RequestContext, plan: AgentPlan) -> ValidationResult:
        """
        Validate a plan generated by the planner.

        Args:
            user_request: The original user request
            request_context: Contextual information for the request
            plan: The plan to validate

        Returns:
            ValidationResult: Result of the validation
        """
        self.logger.info(f"Validating plan for request {user_request.request_id}")

        errors = []
        warnings = []
        normalized_arguments = {}

        if plan.request_id != user_request.request_id:
            errors.append("Plan request ID does not match the original request")

        # Validate basic plan structure
        if not plan.operations:
            errors.append("Plan contains no operations")
            return ValidationResult(valid=False, errors=errors, warnings=warnings)

        # Validate each operation
        validated_operations = []
        operation_ids = set()

        for i, operation in enumerate(plan.operations):
            op_result = self._validate_operation(operation, user_request, request_context, operation_ids)
            if not op_result.valid:
                errors.extend(op_result.errors)
            else:
                validated_operations.append(operation)
                if op_result.normalized_arguments:
                    # In a real implementation, we would merge normalized arguments
                    pass

            warnings.extend(op_result.warnings)

        # Check for circular dependencies
        dependency_errors = self._check_dependencies(validated_operations)
        errors.extend(dependency_errors)

        # If no errors, create normalized plan
        if not errors:
            pending = list(validated_operations)
            ordered_operations = []
            completed_ids = set()
            while pending:
                ready = [op for op in pending if set(op.dependencies).issubset(completed_ids)]
                if not ready:
                    break
                for operation in ready:
                    ordered_operations.append(operation)
                    completed_ids.add(operation.operation_id)
                    pending.remove(operation)
            validated_operations = ordered_operations
            normalized_arguments = {
                "operations": [
                    {
                        "operation_id": op.operation_id,
                        "capability": op.capability,
                        "arguments": op.arguments,
                        "dependencies": op.dependencies,
                        "reason": op.reason,
                        "context_requirements": op.context_requirements
                    }
                    for op in validated_operations
                ]
            }

        valid = len(errors) == 0

        self.logger.info(f"Validation completed for request {user_request.request_id}: valid={valid}, errors={len(errors)}, warnings={len(warnings)}")

        return ValidationResult(
            valid=valid,
            errors=errors,
            warnings=warnings,
            normalized_arguments=normalized_arguments if valid else None
        )

    def _validate_operation(self, operation: PlannedOperation, user_request: UserRequest, request_context: RequestContext, existing_operation_ids: set) -> ValidationResult:
        """Validate a single operation.

        Args:
            operation: The operation to validate
            user_request: The original user request
            request_context: Contextual information for the request
            existing_operation_ids: Set of operation IDs already processed

        Returns:
            ValidationResult: Result of the validation
        """
        errors = []
        warnings = []
        normalized_arguments = {}

        # Check for duplicate operation IDs
        if operation.operation_id in existing_operation_ids:
            errors.append(f"Duplicate operation ID: {operation.operation_id}")
            return ValidationResult(valid=False, errors=errors, warnings=warnings)

        # Validate operation ID
        if not operation.operation_id or not operation.operation_id.strip():
            errors.append("Operation ID is required")

        # Validate capability
        if not operation.capability or not operation.capability.strip():
            errors.append("Capability is required")
        elif operation.capability not in self._allowed_capabilities:
            errors.append(f"Unknown capability: {operation.capability}")

        # Validate arguments (basic validation)
        if not isinstance(operation.arguments, dict):
            errors.append("Arguments must be a dictionary")

        # Validate dependencies
        if not isinstance(operation.dependencies, list):
            errors.append("Dependencies must be a list")
        else:
            for dep in operation.dependencies:
                if not isinstance(dep, str) or not dep.strip():
                    errors.append("Dependency must be a non-empty string")

        # Validate reason
        if not operation.reason or not operation.reason.strip():
            errors.append("Reason is required")

        # Validate context requirements
        if not isinstance(operation.context_requirements, list):
            errors.append("Context requirements must be a list")
        else:
            for req in operation.context_requirements:
                if not isinstance(req, str) or not req.strip():
                    errors.append("Context requirement must be a non-empty string")

        # Context requirements must be satisfied by actual request context.
        missing_context = []
        for req in operation.context_requirements:
            if req not in {"image", "video", "user", "plant", "scan", "location", "conversation", "previous_results"}:
                errors.append(f"Unsupported context requirement: {req}")
            elif getattr(request_context, req, None) is None:
                missing_context.append(req)

        if missing_context:
            errors.append(f"Missing context for operation {operation.operation_id}: {', '.join(missing_context)}")

        valid = len(errors) == 0

        return ValidationResult(
            valid=valid,
            errors=errors,
            warnings=warnings,
            normalized_arguments={"operation": operation.dict()} if valid else None
        )

    def _check_dependencies(self, operations: List[PlannedOperation]) -> List[str]:
        """Check for circular dependencies and missing dependencies.

        Args:
            operations: List of operations to check

        Returns:
            List[str]: List of dependency errors
        """
        errors = []
        operation_ids = {op.operation_id for op in operations}

        # Build dependency graph
        dependency_map = {}
        for op in operations:
            dependency_map[op.operation_id] = set(op.dependencies)

        # Check for missing dependencies
        for op in operations:
            for dep in op.dependencies:
                if dep not in operation_ids:
                    errors.append(f"Operation {op.operation_id} depends on non-existent operation: {dep}")

        graph = {op.operation_id: set(op.dependencies) for op in operations}
        state: Dict[str, int] = {}

        def visit(operation_id: str) -> bool:
            state[operation_id] = 1
            for dependency in graph[operation_id]:
                if dependency not in graph:
                    continue
                if state.get(dependency) == 1:
                    return True
                if state.get(dependency, 0) == 0 and visit(dependency):
                    return True
            state[operation_id] = 2
            return False

        if any(state.get(operation_id, 0) == 0 and visit(operation_id) for operation_id in graph):
            errors.append("Circular operation dependency detected")

        return errors
