"""
Agent Plan Contract
Defines the structure of plans generated by the planner.
"""
from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
from .planned_operation import PlannedOperation


class AgentPlan(BaseModel):
    """
    Structured plan generated by the planner.

    Attributes:
        request_id: Identifier of the original user request
        operations: List of planned operations to execute
        timestamp: When the plan was generated
        reasoning: Optional explanation of the planning approach
    """
    request_id: str = Field(..., description="Identifier of the original user request")
    operations: List[PlannedOperation] = Field(..., description="List of planned operations to execute")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the plan was generated")
    reasoning: Optional[str] = Field(None, description="Optional explanation of the planning approach")

    class Config:
        json_schema_extra = {
            "example": {
                "request_id": "req_123456789",
                "operations": [
                    {
                        "operation_id": "op_1",
                        "capability": "leaf_segmentation",
                        "arguments": {},
                        "reason": "First, segment leaves from the whole plant image"
                    },
                    {
                        "operation_id": "op_2",
                        "capability": "disease_classification",
                        "arguments": {"leaf_index": 0},
                        "reason": "Then, classify disease for the first leaf",
                        "dependencies": ["op_1"]
                    }
                ],
                "timestamp": "2026-09-24T10:30:00Z",
                "reasoning": "Sequential processing: segment leaves first, then classify disease"
            }
        }