"""
Execution Command Contract
Defines the structure of safe internal execution commands.
"""
from pydantic import BaseModel, Field
from typing import Dict, Any
from datetime import datetime


class ExecutionCommand(BaseModel):
    """
    Safe internal execution command generated by the command builder.

    Attributes:
        command_id: Unique identifier for this execution command
        operation_id: Corresponding operation ID from the plan
        capability: The capability to execute
        service_method: The specific service method to call
        service_args: Arguments to pass to the service method
        timestamp: When the command was generated
    """
    command_id: str = Field(..., description="Unique identifier for this execution command")
    operation_id: str = Field(..., description="Corresponding operation ID from the plan")
    capability: str = Field(..., description="The capability to execute")
    service_method: str = Field(..., description="The specific service method to call")
    service_args: Dict[str, Any] = Field(default_factory=dict, description="Arguments to pass to the service method")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the command was generated")

